##################################################
# NovaCart Auth API - REST Client
##################################################

@baseUrl = http://127.0.0.1:8000/api/auth

##################################################
# USER REGISTRATION
##################################################

### Register User
POST {{baseUrl}}/register/
Content-Type: application/json

{
    "email": "duncanoyugi2001@gmail.com",
    "full_name": "Duncan Ochieng",
    "phone_number": "+254711592572",
    "password": "Dante@1234",
    "password2": "Dante@1234"
}

##################################################
# OTP VERIFICATION
##################################################

### Verify OTP
POST {{baseUrl}}/verify-otp/
Content-Type: application/json

{
    "email": "ochiengduncan7878@gmail.com",
    "otp_code": "219446"
}

##################################################
# RESEND OTP
##################################################

### Resend OTP
POST {{baseUrl}}/resend-otp/
Content-Type: application/json

{
    "email": "duncanoyugi2001@gmail.com"
}

##################################################
# RESEND WELCOME EMAIL
##################################################

### Resend Welcome Email
POST {{baseUrl}}/resend-welcome/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "email": "duncanoyugi2001@gmail.com"
}

##################################################
# USER LOGIN
##################################################

### Login User (Customer)
POST {{baseUrl}}/login/
Content-Type: application/json

{
    "email": "duncanoyugi2001@gmail.com",
    "password": "Dante@1234"
}

##################################################
# ADMIN LOGIN
##################################################

### Login Admin
POST {{baseUrl}}/login/
Content-Type: application/json

{
    "email": "admin@novacart.com",
    "password": "Admin@123456"
}

##################################################
# GET CURRENT AUTHENTICATED USER
##################################################

### Get Current User
GET {{baseUrl}}/me/
Authorization: Bearer {{access_token}}

##################################################
# REFRESH JWT TOKEN
##################################################

### Refresh Access Token
POST {{baseUrl}}/refresh/
Content-Type: application/json

{
    "refresh": "{{refresh_token}}"
}

##################################################
# USER LOGOUT
##################################################

### Logout User
POST {{baseUrl}}/logout/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "refresh": "{{refresh_token}}"
}