# Generated by Django 6.0.5 on 2026-06-21 00:06

from django.db import migrations, migrations
from django.db.models import CharField, DecimalField


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
