# Generated by Django 6.0.5 on 2026-06-21 00:06

from django.db import migrations
from django.db.models import CharField, DecimalField


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        # This migration is now redundant: `coupon_code` and `coupon_discount`
        # are already included in `orders.0001_initial`.
        # Keeping it as a no-op avoids "column already exists" failures when
        # building fresh test databases.
    ]
