# Generated by Django 6.0.5 on 2026-06-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_billing_full_name'),
        ('orders', '0005_fix_billing_address_line2'),
    ]

    operations = [
    ]
