# Generated by Django 6.0.5 on 2026-06-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_billing_address_line2_and_more'),
    ]

    operations = [
    ]
