# Generated by Django 6.0.5 on 2026-06-22 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_add_all_missing_columns'),
        ('orders', '0010_add_variant_attributes_column'),
    ]

    operations = [
    ]
