# Generated by Django 6.0.5 on 2026-05-28 20:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('page_url', models.CharField(max_length=500)),
                ('referrer_url', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_page_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='analytics_p_user_id_bbd762_idx'), models.Index(fields=['session_key'], name='analytics_p_session_52bcdc_idx'), models.Index(fields=['page_url'], name='analytics_p_page_ur_c3e732_idx'), models.Index(fields=['viewed_at'], name='analytics_p_viewed__a5f8fc_idx'), models.Index(fields=['country'], name='analytics_p_country_e92075_idx')],
            },
        ),
    ]
