# Generated by Django 6.0.5 on 2026-06-21 01:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_missing_order_columns'),
        ('products', '0001_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_helpful', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_helpful',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='not_helpful_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='review',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Approved by admin'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, help_text='User actually purchased this product'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-helpful_count'], name='reviews_helpful_b761c2_idx'),
        ),
        migrations.AddField(
            model_name='reviewhelpful',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='reviewhelpful',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reviewhelpful',
            index=models.Index(fields=['review'], name='review_help_review__606aca_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewhelpful',
            index=models.Index(fields=['user'], name='review_help_user_id_aa9b90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpful',
            unique_together={('review', 'user')},
        ),
    ]
