# Generated by Django 6.0.5 on 2026-06-20 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='stripe', max_length=50)),
                ('event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'processed_webhook_events',
                'indexes': [models.Index(fields=['provider', 'event_id'], name='processed_w_provide_16e5d4_idx'), models.Index(fields=['processed_at'], name='processed_w_process_ba066e_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_processed_webhook_event')],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('response_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.payment')),
            ],
            options={
                'db_table': 'payment_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stripe_payment_intent_id'], name='payment_att_stripe__eec25c_idx'), models.Index(fields=['created_at'], name='payment_att_created_40e5df_idx')],
            },
        ),
    ]
